### PR TITLE
event propagation

### PR DESCRIPTION
**Pull request by enrico-bardelli**
added event object parameter to setFocus and navigateByDirection
added event object parameter to onBecameBlurred and onBecameFocused
onBecameBlurred and onBecameFocused called synchronously with navigation

### CODE REVIEW

**Review by predikament — DISMISSED** [review]
Looks'a good'a 👍

**Review by JakubKubista — DISMISSED** [review]

**Review by asgvard — COMMENTED** [review]
We have to check something regarding the new condition of setting focus only when focus key changed. It could potentially break the behavior of “lazy focus when item appears later then the focus key was set”

**Comment by salvan13** [comment]
- I suggest to encapsulate the event in a "details" object, then if we will need to add more info we will not need to add other parameters but we can add them in that object
- the documentation (in readme) should be updated

**Review by predikament — DISMISSED** [review]
Looks'a better'a 👍

**Review by asgvard — DISMISSED** [review]
Looks good in my opinion.
But please double check with Antonio regarding "details" object.

**Review by salvan13 — APPROVED** [review]

**Review by asgvard — APPROVED** [review]

**Pull request merged**
